service: nba-dfs

provider:
  name: aws
  runtime: python3.8
  profile: serverless-nba-dfs

functions:
  main:
    handler: lambda_pipeline.driver_fn
    # if this line isn't here serverless-python-requirements causes error
    package: {}

plugins:
  # bundles dependencies found in Pipfile when deploying
  - serverless-python-requirements
